name: TypeScript
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string

env:
  ALUMNIUM_LOG_LEVEL: debug
  ALUMNIUM_LOG_DEBUG_EXTRA: all
  ALUMNIUM_LOG_PATH: alumnium.log
  ALUMNIUM_PLAYWRIGHT_HEADLESS: false
  DISPLAY: :99
  LT_USERNAME: ${{ secrets.LT_USERNAME }}
  LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
  AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
  AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
  DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  test-system:
    name: System Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      ALUMNIUM_DRIVER: ${{ matrix.driver }}
      ALUMNIUM_MODEL: ${{ matrix.model }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - driver: selenium
            model: azure_openai

          - driver: playwright
            model: azure_openai

          - driver: playwright
            model: google

          # TODO: Figure out why LambdaTest started to fail.

          # - driver: appium-ios
          #   model: azure_openai

    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Set Up Dev Env
        uses: ./.github/actions/setup

      - name: Test System
        uses: ./.github/actions/test-system
        with:
          package: typescript
          driver: ${{ matrix.driver }}
          model: ${{ matrix.model }}
          sha: ${{ inputs.sha }}

      - name: Build Dist
        run: mise //packages/typescript:build

      - name: Upload Test Artifacts
        if: always()
        uses: ./.github/actions/test-artifacts
        with:
          name: system-${{ matrix.driver }}-${{ matrix.model }}
          typescript: true

      - name: Debug Session
        if: failure() && runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

  test-pkg:
    name: Package Tests
    runs-on: ubuntu-latest
    env:
      ALUMNIUM_MODEL: azure_openai

    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Set Up Dev Env
        uses: ./.github/actions/setup

      - name: Build Dist
        run: mise //packages/typescript:build

      - name: Run npm Tests
        run: mise //packages/typescript:test/package

      - name: Debug Session
        if: failure() && runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Set Up Dev Env
        uses: ./.github/actions/setup

      - name: Build Dist
        run: mise //packages/typescript:build

      - name: Upload npm Artifacts
        uses: ./.github/actions/dist-artifacts
        with:
          name: build
          npm: true

      - name: Debug Session
        if: failure() && runner.debug == '1'
        uses: mxschmitt/action-tmate@v3
